name: Backend - Evaluaciones Rosario  

on:
  push:
    branches: ["master"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Copiar archivos al servidor
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "."
          target: "/home/ubuntu/mozart2.0agentes"

      - name: Ejecutar comandos en EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ubuntu/mozart2.0agentes

            echo "Instalando dependencias..."
            npm install --production

            echo "Reiniciando backend..."
            pm2 delete backend-agentes-intitutofracturas
            
            pm2 start index.js --name backend-agentes-intitutofracturas

            pm2 save

            echo "Deploy finalizado correctamente"